# site settings
title: Pablo Vicente Munuera
subtitle: "postdoctoral researcher"
email: p.munuera@ucl.ac.uk
description: "Computational biology, tissue mechanics and cell biology"
baseurl: "" # the subpath of your site, e.g. /blog
url: 
author:
street_address: "Laboratory for Molecular Cell Biology (LMCB)"
city: University College London
state: London
zip_code: 
country: UK

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/pablo1990
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/pablovm1990
  Twitter: https://twitter.com/pvicentemunuera
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
